---
data:
  # doris-rinex: data/Jason-3/ja3rx21002.001
  doris-rinex: data/Jason-3/ja3rx22248.001
  # sp3: data/Jason-3/ssaja320.b20362.e21006.DG_.sp3.001
  # sp3: data/Sentinel-6A/ssas6a20.b20362.e21006.DG_.sp3.001
  sp3: data/Jason-3/ssaja320.b22238.e22258.DG_.sp3.001

reference-frame:
  # station-coordinates: data/dpod2014_053.snx
  station-coordinates: data/dpod2020_01.snx

eop-info:
  # eop-file: data/EOP_14_C04_IAU2000A_one_file_1962-now.txt
  eop-file: data/eopc0420.1962-now

naif-kernels:
  spk: data/jpl/de421.bsp
  pck: data/jpl/gm_de431.tpc
  lsk: data/jpl/naif0012.tls

ocean-tides:
  harmonics: data/oceanTide_FES2014b.potential.iers.txt
  degree: 80
  order: 80
  blq: data/fes14b.blq
  
gravity:
  # model: data/gfc/GOCO02s.gfc
  # model: data/gfc/EIGEN-GRGS.RL04.MEAN-FIELD.linear_mean_pole.zero_slope_extrapolation.gfc2
  model: data/gfc/EIGEN-GRGS.RL04.MEAN-FIELD.gfc
  degree: 120
  order: 120

troposphere:
  gpt3:
    grid: data/gpt3_5.grd
  vmf3:
    grid: data/2022248.v3gr_d

force-model:
  atmospheric-drag:
    # drag-model: nrlmsise00
    dtm2020-data: data/DTM_2020_F107_Kp.dat
    atmo-data-csv: data/SW-All.csv
    ## working value is 2e0
    Cd-apriori: 1e0
  srp:
    Cr-apriori: 1e0

attitude:
  mass-cog: data/Jason-3/ja3mass.txt
  body-quaternion: data/Jason-3/ja3qbody20220904220000_20220906020000.001
  solar-array: data/Jason-3/ja3solararray.

filtering:
  ## Units: [m/sec]
  observation-sigma: 5e-3
  ## A-priori sigma for Î”fe / feN
  deffen-sigma: 1e-1
  ## A-priori sigma for initial state/position (sp3)
  orbsp3-sigma-pos: 2e0
  ## A-priori sigma for initial state/velocity (sp3)
  orbsp3-sigma-vel: 1e0
  ## A-priori sigma for Cd (aka drag coefficient)
  #cd-sigma: .5e0
  cd-sigma: 1e0
  ## A-priori sigma for Cr (aka srp coefficient)
  #cr-sigma: .1e0 also  note the chane in pod.cpp 1param/day
  cr-sigma: 1e-1
  ## Units: [degrees]
  elevation-cut-off: 10e0 ## in degrees
