---
data:
  doris-rinex: data/Saral/srlrx21002.001
  sp3: data/Saral/ssasrl20.b20362.e21004.D__.sp3.001
  beacon-information: data/beacon_information.tbl

reference-frame:
  station-coordinates: data/dpod2014_053.snx

eop-info:
  eop-file: data/bulb0121

naif-kernels:
  spk: data/jpl/de405.bsp
  pck: data/jpl/gm_de431.tpc
  lsk: data/jpl/naif0012.tls

gravity:
  model: data/gfc/GOCO02s.gfc
  degree: 20
  order: 20

troposphere:
  gpt3:
    grid: data/gpt3_5.grd

force-model:
  atmospheric-drag:
    drag-model: nrlmsise00
    atmo-data-csv: data/SW-All.csv
