---
data:
  doris-rinex: data/Jason-3/ja3rx21002.001
  sp3: data/Jason-3/ssaja320.b20362.e21006.DG_.sp3.001
  beacon-information: data/beacon_information.tbl

reference-frame:
  station-coordinates: data/dpod2014_053.snx

eop-info:
  # eop-file: data/eopc04_14_IAU2000.62-now.txt
  eop-file: data/EOP_14_C04_IAU2000A_one_file_1962-now.txt

naif-kernels:
  spk: data/jpl/de405.bsp
  pck: data/jpl/gm_de431.tpc
  lsk: data/jpl/naif0012.tls

gravity:
  # model: data/gfc/GOCO02s.gfc
  model: data/gfc/EIGEN-GRGS.RL04.MEAN-FIELD.linear_mean_pole.zero_slope_extrapolation.gfc2
  # model: data/gfc/EIGEN-GRGS.RL04.MEAN-FIELD.gfc
  degree: 120
  order: 120

troposphere:
  gpt3:
    grid: data/gpt3_5.grd
  vmf3:
    grid: data/y2021.v3gr_d

force-model:
  atmospheric-drag:
    drag-model: nrlmsise00
    atmo-data-csv: data/SW-All.csv

attitude:
  mass-cog: data/Jason-3/ja3mass.txt
  body-quaternion: data/Jason-3/ja3qbody20210101220000_20210103020000.001

filtering:
  ## Units: [m/sec]
  observation-sigma: .5e0
  ## Units: [degrees]
  elevation-cut-off: 15e0 ## in degrees
